//! Turns the scanned [`Registry`] into `CodeGeneratorResponse` files.
//!
//! One Rust file per proto *package*, `<package>.aip.rs`, plus the module tree
//! that mounts them. Per package rather than per source `.proto` to match
//! `protoc-gen-buffa` under `file_per_package=true`, which is what a consumer
//! of both ends up with: `example.v1.rs` and `example.v1.aip.rs`, side by side
//! and includable into the same module. The `.aip` says which plugin wrote it,
//! so several extending the same package can share a directory.

pub mod behavior;
pub mod field_mask;
pub mod query;
pub mod resource;

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result, anyhow};
use buffa_codegen::generated::{
    compiler::{CodeGeneratorRequest, code_generator_response::File},
    descriptor::FileDescriptorProto,
};
use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use crate::messages::{Index, Message};
use crate::scan::Registry;

/// The header on every emitted file.
const HEADER: &str = "// @generated by protoc-gen-rust-aip. DO NOT EDIT.\n";

/// Plugin options, parsed from `opt:` in `buf.gen.yaml`.
#[derive(Debug, Clone)]
pub struct Options {
    /// The Rust module the buffa-generated message types live under.
    ///
    /// Each leaf of the emitted module tree does `use <proto_module>::<pkg>::*`
    /// so the accessors emitted for a message can name it unqualified. Read
    /// only when [`packaging`](Self::packaging) is on, since that tree is the
    /// only thing it appears in.
    pub proto_module: String,

    /// Whether to emit the module tree that mounts the per-file output:
    /// `mod.rs` and one `<package>.mod.rs` per package.
    ///
    /// On by default, which is what a consumer mounting the whole tree with
    /// `include!("aip/mod.rs")` needs.
    ///
    /// Off for a consumer that instead includes the per-file output into the
    /// module already holding the message types, so the resource names sit
    /// beside the resources rather than in a parallel tree. Then the packaging
    /// files are not merely unused — a `mod.rs` written into the same directory
    /// as a hand-written one silently replaces it, which `buf generate` reports
    /// as success.
    ///
    /// Turning it off constrains the schema: the per-file output names a
    /// same-package type by its short name but reaches another package with
    /// `super` hops counted from the root of this tree, so a consumer that does
    /// not mount the tree can only resolve those hops for a single-package
    /// schema.
    pub packaging: bool,

    /// Whether to emit each read-only accessor for buffa's borrowed view type
    /// as well as for the owned message.
    ///
    /// Off by default, because a view type only exists if `buffa` generated
    /// one, and emitting `impl FooView<'_>` when it did not is a compile error
    /// in the consumer rather than a missing method. There is nothing in a
    /// `CodeGeneratorRequest` that says whether views were generated, so this
    /// has to be told.
    ///
    /// Worth turning on for a connectrpc server: a handler is passed a
    /// `ServiceRequest` that derefs to the *view*, so without this the
    /// accessors are emitted onto a type the handler never holds.
    ///
    /// Only the read-only accessors are doubled. `clear_output_only` takes
    /// `&mut self`, and a view does not own what it would clear.
    pub views: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            proto_module: "crate::proto".to_owned(),
            packaging: true,
            views: false,
        }
    }
}

/// Renders the response files for everything in `request.file_to_generate`.
///
/// One `<package>.aip.rs` per proto package, plus — unless
/// [`Options::packaging`] is off — the `mod.rs` that mounts them.
///
/// A package whose files declare no resource and reference none produces no
/// output at all, rather than an empty file the consumer would still have to
/// mount.
///
/// # Errors
///
/// If a file scheduled for generation is not in the request, if emitted tokens
/// do not parse as Rust — which is a bug in this crate, reported with the
/// tokens — or if `proto_module` is not a Rust path.
pub fn render(
    request: &CodeGeneratorRequest,
    registry: &Registry,
    index: &Index,
    options: &Options,
) -> Result<Vec<File>> {
    let by_name: BTreeMap<&str, &FileDescriptorProto> = request
        .proto_file
        .iter()
        .map(|file| (file.name.as_deref().unwrap_or_default(), file))
        .collect();

    let generated: BTreeSet<String> = request.file_to_generate.iter().cloned().collect();
    let walks = behavior::plan(index, &generated);
    let lists = query::plan(index);

    // Proto package to what each of its files emitted, concatenated in
    // `file_to_generate` order so the output is stable across runs.
    let mut by_package: BTreeMap<String, Vec<TokenStream>> = BTreeMap::new();

    for name in &request.file_to_generate {
        let descriptor = by_name
            .get(name.as_str())
            .ok_or_else(|| anyhow!("{name} is scheduled for generation but not in the request"))?;
        let package = descriptor.package.clone().unwrap_or_default();

        let resources = resource::emit_file(name, &package, registry, options.views);
        let creates = resource::emit_create_ids(name, index, registry, options.views);
        let behaviors = behavior::emit_file(name, index, &walks, &generated);
        let masks = field_mask::emit_file(name, index, registry);
        let queries = query::emit_file(name, index, &lists, &generated);
        if resources.is_empty()
            && creates.is_empty()
            && behaviors.is_empty()
            && masks.is_empty()
            && queries.is_empty()
        {
            continue;
        }
        by_package
            .entry(package)
            .or_default()
            .push(quote! { #resources #creates #behaviors #masks #queries });
    }

    let mut files = Vec::new();
    for (package, bodies) in &by_package {
        let path = package_file(package);
        let content = format(
            &quote! {
                // Brings the buffa message types into scope: mounted by the
                // module tree, or already present in the module a consumer
                // included this into. A package that declares only resource
                // names references none of them, hence the allow.
                #[allow(unused_imports, clippy::wildcard_imports)]
                use super::*;
                #( #bodies )*
            },
            &path,
        )?;
        files.push(file(path, content));
    }

    if files.is_empty() || !options.packaging {
        return Ok(files);
    }

    files.push(file(
        "mod.rs".to_owned(),
        module_tree(&by_package, options)?,
    ));
    Ok(files)
}

/// The file a package's output is written to.
///
/// One per package, so the module tree includes it directly and there is no
/// intermediate `<package>.mod.rs` between the two.
fn package_file(package: &str) -> String {
    format!("{package}.aip.rs")
}

fn file(name: String, content: String) -> File {
    File {
        name: Some(name),
        content: Some(content),
        insertion_point: None,
        generated_code_info: None.into(),
        ..Default::default()
    }
}

/// Parses `tokens` as a Rust file and renders it, so the output is readable
/// rather than one line of `TokenStream`.
fn format(tokens: &TokenStream, label: &str) -> Result<String> {
    let parsed: syn::File = syn::parse2(tokens.clone()).map_err(|error| {
        // The tokens go into the message because this failing means the
        // generator emitted something ill-formed, and the tokens are the only
        // evidence of what.
        anyhow!(
            "emitted tokens for {label} do not parse: {error}\n\
             --- BEGIN TOKENS ---\n{tokens}\n--- END TOKENS ---"
        )
    })?;
    Ok(format!("{HEADER}{}", prettyplease::unparse(&parsed)))
}

/// The last segment of a fully-qualified proto name.
fn short_name(fqn: &str) -> &str {
    fqn.rsplit('.').next().unwrap_or(fqn)
}

/// How many `super` hops reach the root of the emitted tree from `package`.
fn package_depth(package: &str) -> usize {
    if package.is_empty() {
        0
    } else {
        package.split('.').count()
    }
}

/// The path by which code emitted into `from`'s file names the message `target`.
///
/// Within one package the short path is enough. Across packages it walks up to
/// the root of the emitted module tree and back down, so it resolves wherever
/// the consumer mounts that tree -- an absolute `crate::` path would have to be
/// configured, and would be wrong the moment it was not.
///
/// The same rule [`resource::type_path`] applies to name types, over the message
/// index rather than the resource registry.
fn type_path_in(from: &Message, index: &Index, target: &str) -> TokenStream {
    let Some(message) = index.get(target) else {
        // Unreachable for a target the caller took from the index, which is
        // every caller; an unresolvable name is better as a compile error in
        // the consumer than as a silently dropped method.
        let name: TokenStream = short_name(target)
            .parse()
            .expect("a proto identifier is a valid Rust identifier");
        return name;
    };
    let path: TokenStream = message
        .rust_path
        .parse()
        .expect("a message path built from proto identifiers is a valid Rust path");
    if message.package == from.package {
        return path;
    }
    let ups = std::iter::repeat_n(quote! { super }, package_depth(&from.package));
    let downs = message
        .package
        .split('.')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let segment = format_ident!("{}", buffa_codegen::idents::escape_mod_ident(segment));
            quote! { #segment }
        });
    quote! { #( #ups :: )* #( #downs :: )* #path }
}

/// Emits `body` as an inherent impl on `path`, and again on its buffa view type
/// when `views` is on.
///
/// The bodies are token-identical, which is not a coincidence worth hiding: an
/// accessor reads a field, and a view's field holds `&str` where the owned
/// message holds `String`. Every operation these accessors perform on one --
/// `is_empty`, `&self.field` into a `&str` parameter, `as_option` -- is spelled
/// the same for the other, so the tokens are shared rather than re-derived.
fn impl_for(path: &TokenStream, view: bool, body: &TokenStream) -> TokenStream {
    let owned = quote! { impl #path { #body } };
    if !view {
        return owned;
    }
    let view = view_path(path);
    quote! {
        #owned
        // On the view copy only, so the owned impl keeps full coverage. A view
        // holds `&str` where the owned message holds `String`, so `&self.field`
        // is the borrow the owned form needs and one deref too many here --
        // which is the price of the two impls sharing one body.
        #[allow(
            clippy::needless_borrow,
            reason = "the borrow is required by the owned impl these tokens are shared with"
        )]
        impl #view <'_> { #body }
    }
}

/// buffa names the borrowed form of `Foo` as `FooView<'a>`, so the view of a
/// path is its last segment with `View` appended.
fn view_path(path: &TokenStream) -> TokenStream {
    let rendered = path.to_string().replace(' ', "");
    let (module, name) = match rendered.rsplit_once("::") {
        Some((module, name)) => (format!("{module}::"), name.to_owned()),
        None => (String::new(), rendered),
    };
    format!("{module}{name}View")
        .parse()
        .expect("a view path built from a message path is a valid Rust path")
}

/// Renders `text` as a doc comment.
///
/// Emitted as `#[doc = "..."]` per line rather than as `///`, which a
/// `TokenStream` has no way to spell.
fn doc(text: &str) -> TokenStream {
    let lines: Vec<TokenStream> = text
        .lines()
        .map(|line| {
            let line = Literal::string(&format!(" {line}"));
            quote! { #[doc = #line] }
        })
        .collect();
    quote! { #( #lines )* }
}

/// One node of the proto-package trie the module tree mirrors.
#[derive(Default)]
struct Node {
    children: BTreeMap<String, Self>,
    /// Set when a package's own file is mounted at this node.
    package: Option<String>,
}

/// The top-level `mod.rs`: nested `pub mod` blocks mirroring each proto
/// package, each leaf pulling in that package's file and bringing the matching
/// buffa module into scope so the emitted `impl` blocks resolve their message
/// types by short name.
fn module_tree(
    by_package: &BTreeMap<String, Vec<TokenStream>>,
    options: &Options,
) -> Result<String> {
    let mut root = Node::default();
    for package in by_package.keys() {
        let mut node = &mut root;
        for segment in package.split('.').filter(|s| !s.is_empty()) {
            node = node.children.entry(segment.to_owned()).or_default();
        }
        node.package = Some(package.clone());
    }

    let proto_module: syn::Path = syn::parse_str(&options.proto_module)
        .with_context(|| format!("proto_module {:?} is not a Rust path", options.proto_module))?;
    // Outer attributes only, never a file-level `#![allow(..)]`: a consumer
    // that mounts this with `include!` rather than `#[path]` cannot carry inner
    // attributes through the macro expansion, and which of the two they use is
    // not this plugin's business.
    let body = node_tokens(&root, &[], &proto_module);
    format(&body, "mod.rs")
}

fn node_tokens(node: &Node, path: &[&str], proto_module: &syn::Path) -> TokenStream {
    let leaf = node
        .package
        .as_ref()
        .map_or_else(TokenStream::new, |package| {
            let segments: Vec<syn::Ident> = path.iter().map(|s| format_ident!("{}", s)).collect();
            let include = Literal::string(&package_file(package));
            // Terse `allow`s, without the `reason` this crate writes for itself:
            // this file is machine-generated and read at a glance, and a paragraph
            // above every `use` buries the three lines that carry information.
            quote! {
                #[allow(unused_imports, clippy::wildcard_imports)]
                use #proto_module #( :: #segments )* ::*;
                include!(#include);
            }
        });
    let children: Vec<TokenStream> = node
        .children
        .iter()
        .map(|(segment, child)| {
            let ident = format_ident!("{}", buffa_codegen::idents::escape_mod_ident(segment));
            let mut next = path.to_vec();
            next.push(segment);
            let inner = node_tokens(child, &next, proto_module);
            quote! {
                #[allow(clippy::module_inception)]
                pub mod #ident {
                    #[allow(unused_imports, clippy::wildcard_imports)]
                    use super::*;
                    #inner
                }
            }
        })
        .collect();
    quote! {
        #leaf
        #( #children )*
    }
}
