//! Turns the scanned [`Registry`] into `CodeGeneratorResponse` files.
//!
//! One Rust file per source `.proto`, plus the module tree that mounts them.
//! The layout matches `protoc-gen-buffa` and `protoc-gen-protovalidate-buffa`
//! so all three plugins' output drops into a consumer the same way — and so a
//! generated file can be `include!`d into the module that already holds the
//! message types it extends.

pub mod behavior;
pub mod query;
pub mod resource;

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result, anyhow};
use buffa_codegen::generated::{
    compiler::{CodeGeneratorRequest, code_generator_response::File},
    descriptor::FileDescriptorProto,
};
use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use crate::messages::Index;
use crate::scan::Registry;

/// The header on every emitted file.
const HEADER: &str = "// @generated by protoc-gen-rust-aip. DO NOT EDIT.\n";

/// Plugin options, parsed from `opt:` in `buf.gen.yaml`.
#[derive(Debug, Clone)]
pub struct Options {
    /// The Rust module the buffa-generated message types live under.
    ///
    /// Each leaf of the emitted module tree does `use <proto_module>::<pkg>::*`
    /// so the accessors emitted for a message can name it unqualified.
    pub proto_module: String,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            proto_module: "crate::proto".to_owned(),
        }
    }
}

/// Renders the response files for everything in `request.file_to_generate`.
///
/// A file that declares no resource and references none produces no output at
/// all, rather than an empty file the consumer would still have to mount.
///
/// # Errors
///
/// If a file scheduled for generation is not in the request, if emitted tokens
/// do not parse as Rust — which is a bug in this crate, reported with the
/// tokens — or if `proto_module` is not a Rust path.
pub fn render(
    request: &CodeGeneratorRequest,
    registry: &Registry,
    index: &Index,
    options: &Options,
) -> Result<Vec<File>> {
    let by_name: BTreeMap<&str, &FileDescriptorProto> = request
        .proto_file
        .iter()
        .map(|file| (file.name.as_deref().unwrap_or_default(), file))
        .collect();

    let generated: BTreeSet<String> = request.file_to_generate.iter().cloned().collect();
    let walks = behavior::plan(index, &generated);
    let lists = query::plan(index);

    let mut files = Vec::new();
    // Proto package to the files emitted for it, so the module tree can mount
    // each one under the right nesting.
    let mut by_package: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for name in &request.file_to_generate {
        let descriptor = by_name
            .get(name.as_str())
            .ok_or_else(|| anyhow!("{name} is scheduled for generation but not in the request"))?;
        let package = descriptor.package.clone().unwrap_or_default();

        let resources = resource::emit_file(name, &package, registry);
        let behaviors = behavior::emit_file(name, index, &walks, &generated);
        let queries = query::emit_file(name, index, &lists, &generated);
        if resources.is_empty() && behaviors.is_empty() && queries.is_empty() {
            continue;
        }
        let body = quote! { #resources #behaviors #queries };

        let path = format!("{}.rs", name.trim_end_matches(".proto").replace('/', "."));
        let content = format(
            &quote! {
                // Brings the buffa message types the module tree mounted into
                // scope. A file that declares only resource names references
                // none of them, hence the allow.
                #[allow(unused_imports, clippy::wildcard_imports)]
                use super::*;
                #body
            },
            &path,
        )?;
        by_package.entry(package).or_default().push(path.clone());
        files.push(file(path, content));
    }

    if files.is_empty() {
        return Ok(files);
    }

    for (package, names) in &by_package {
        let includes: Vec<TokenStream> = names
            .iter()
            .map(|name| {
                let name = Literal::string(name);
                quote! { include!(#name); }
            })
            .collect();
        let path = format!("{package}.mod.rs");
        let content = format(&quote! { #( #includes )* }, &path)?;
        files.push(file(path, content));
    }

    files.push(file(
        "mod.rs".to_owned(),
        module_tree(&by_package, options)?,
    ));
    Ok(files)
}

fn file(name: String, content: String) -> File {
    File {
        name: Some(name),
        content: Some(content),
        insertion_point: None,
        generated_code_info: None.into(),
        ..Default::default()
    }
}

/// Parses `tokens` as a Rust file and renders it, so the output is readable
/// rather than one line of `TokenStream`.
fn format(tokens: &TokenStream, label: &str) -> Result<String> {
    let parsed: syn::File = syn::parse2(tokens.clone()).map_err(|error| {
        // The tokens go into the message because this failing means the
        // generator emitted something ill-formed, and the tokens are the only
        // evidence of what.
        anyhow!(
            "emitted tokens for {label} do not parse: {error}\n\
             --- BEGIN TOKENS ---\n{tokens}\n--- END TOKENS ---"
        )
    })?;
    Ok(format!("{HEADER}{}", prettyplease::unparse(&parsed)))
}

/// Renders `text` as a doc comment.
///
/// Emitted as `#[doc = "..."]` per line rather than as `///`, which a
/// `TokenStream` has no way to spell.
fn doc(text: &str) -> TokenStream {
    let lines: Vec<TokenStream> = text
        .lines()
        .map(|line| {
            let line = Literal::string(&format!(" {line}"));
            quote! { #[doc = #line] }
        })
        .collect();
    quote! { #( #lines )* }
}

/// One node of the proto-package trie the module tree mirrors.
#[derive(Default)]
struct Node {
    children: BTreeMap<String, Self>,
    /// Set when a package's own files are mounted at this node.
    package: Option<String>,
}

/// The top-level `mod.rs`: nested `pub mod` blocks mirroring each proto
/// package, each leaf pulling in that package's files and bringing the matching
/// buffa module into scope so the emitted `impl` blocks resolve their message
/// types by short name.
fn module_tree(by_package: &BTreeMap<String, Vec<String>>, options: &Options) -> Result<String> {
    let mut root = Node::default();
    for package in by_package.keys() {
        let mut node = &mut root;
        for segment in package.split('.').filter(|s| !s.is_empty()) {
            node = node.children.entry(segment.to_owned()).or_default();
        }
        node.package = Some(package.clone());
    }

    let proto_module: syn::Path = syn::parse_str(&options.proto_module)
        .with_context(|| format!("proto_module {:?} is not a Rust path", options.proto_module))?;
    // Outer attributes only, never a file-level `#![allow(..)]`: a consumer
    // that mounts this with `include!` rather than `#[path]` cannot carry inner
    // attributes through the macro expansion, and which of the two they use is
    // not this plugin's business.
    let body = node_tokens(&root, &[], &proto_module);
    format(&body, "mod.rs")
}

fn node_tokens(node: &Node, path: &[&str], proto_module: &syn::Path) -> TokenStream {
    let leaf = node
        .package
        .as_ref()
        .map_or_else(TokenStream::new, |package| {
            let segments: Vec<syn::Ident> = path.iter().map(|s| format_ident!("{}", s)).collect();
            let include = Literal::string(&format!("{package}.mod.rs"));
            // Terse `allow`s, without the `reason` this crate writes for itself:
            // this file is machine-generated and read at a glance, and a paragraph
            // above every `use` buries the three lines that carry information.
            quote! {
                #[allow(unused_imports, clippy::wildcard_imports)]
                use #proto_module #( :: #segments )* ::*;
                include!(#include);
            }
        });
    let children: Vec<TokenStream> = node
        .children
        .iter()
        .map(|(segment, child)| {
            let ident = format_ident!("{}", buffa_codegen::idents::escape_mod_ident(segment));
            let mut next = path.to_vec();
            next.push(segment);
            let inner = node_tokens(child, &next, proto_module);
            quote! {
                #[allow(clippy::module_inception)]
                pub mod #ident {
                    #[allow(unused_imports, clippy::wildcard_imports)]
                    use super::*;
                    #inner
                }
            }
        })
        .collect();
    quote! {
        #leaf
        #( #children )*
    }
}
